# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Charts'

  target 'MyWeatherTests' do
    inherit! :search_paths
    pod 'Charts'
  end

  target 'MyWeatherUITests' do
    pod 'Charts'

  end

end
